version: "3.7"

services:
    scrap:
        image: ${IMAGEURL}
        networks:
            - traefik-network
        environment:
            DSN: ${DSN}
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 10s
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s

networks:
    traefik-network:
        external: true
